### ISSUE TITLE
[Bug] App always crashes when in the Theme Chooser

### ISSUE THREAD

**Issue by collectorgeneral** [micwallace/reddinator#13]
To reproduce this crash, the following steps were done:

- Launch the app -> Settings->Theme Manager.
- Add a new theme, touch back button twice.

Crashes every single time.
Added a video in case you wanted to have a look at it.

Additional info:
Installed from F-Droid.
Phone details:
Oneplus One aka Bacon aka A0001
Running Cyanogen OS 13.1 (Android 6.0.1)
If you need any other info, let me know. 
[Reddinator_Crash_Vid_2_10_Jul_2016.zip](https://github.com/micwallace/reddinator/files/356374/Reddinator_Crash_Vid_2_10_Jul_2016.zip)

**Comment by micwallace** [comment]
Fixed with commit 64c6245
F-Droid should have the latest version in a few days.

Thanks for the report and providing useful information.

**Comment by collectorgeneral** [comment]
F droid has not yet updated the app, can you please look into it?

**Comment by micwallace** [comment]
Yes I forgot to add a new version in github! Just added a new release.
